---
title: "análisis de datos COVID-19 en Costa Rica"
author: "Walter Varela Navarro"
date: '2022-05-11'
output: 
  html_document:
    theme: readable    
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentación
este documento presenta gráficos generados a partir ed los datos de covid- 19 de Costa Rica compartidos por el ministerio de salud en Costa Rica [https://geovision.uned.ac.cr/oges/](https://geovision.uned.ac.cr/oges/)

## Entradas
```{r carga-datos}
covid <- read.csv(file = "05_10_22_CSV_GENERAL.csv", sep =";")
```


## Procesamiento

##### curación de datos
```{r conversión-fecha}
covid$FECHA <- as.Date(covid$FECHA, format = "%d/%m/%Y")

```





### Opciones generales
```{r opciones-generales}
options(scipen = 7)
```


## Salidas

### Gráficos

#### Casos acumulados



##### Positivos

```{r casos-positivos-acumulados}
plot(covid$FECHA,
     covid$positivos,
     type = "l",
     xaxt = "n",
     yaxt = "n",
     main = "Casos acumulados pósitivos de COVID-19 en Costa Rica",
     xlab ="Fecha", 
     ylab ="Casos"
     )
axis(
  side = 1,
  covid$FECHA,
  tick = FALSE,
  format(covid$FECHA, "%m-%y"),
  cex.axis = 0.7
  )
# fromato del eje y
axis(
  side = 2,
  covid$positivos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)
```

##### Fallecidos

```{r casos-covid-fallecidos-acumulados}
plot(covid$FECHA,
     covid$fallecidos,
     type = "l",
     xaxt = "n",
     yaxt = "n",
     main = "fallecidos de COVID-19 en Costa Rica",
     xlab ="Fecha", 
     ylab ="fallecidos"
      )
# Formato eje x
axis(
  side = 1,
  covid$FECHA,
  tick = FALSE,
  format(covid$FECHA, "%m-%y"),
  cex.axis = 0.7
  )
# Formato del eje y
axis(
  side = 2,
  covid$fallecidos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)
```

##### Gráfico de líneas de casos activos

```{r casos-covid- acumulados }
plot(
  covid$FECHA,
     covid$positivos,
     type = "l",
     xaxt = "n",
     yaxt = "n",
     main = "casos acumulados COVID-19 en Costa Rica",
     xlab ="Fecha", 
     ylab ="Casos",
  col = "blue" 
      )
# casos activos
lines(covid$FECHA, covid$activos, col = "red")

#casos recuperados
lines(covid$FECHA, covid$RECUPERADOS, col = "green")

#casos fallecidos
lines(covid$FECHA, covid$fallecidos, col = "black")

# Leyenda
legend(
  x = "topleft",
  inset = 0.03,
  legend = c("Positivos", "Activos", "Recuperados", "Fallecidos"),
  col = c("blue", "red", "green", "black"),
  lty = 1,
  cex = 0.7
)

# Formato eje x
axis(
  side = 1,
  covid$FECHA,
  tick = FALSE,
  format(covid$FECHA, "%m-%y"),
  cex.axis = 0.7
  )
# Formato del eje y
axis(
  side = 2,
  covid$fallecidos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)

```

#### Casoso diarios

##### Positivos

```{r casos-nuevos-positivos}
# Gráfico de barras
barplot(
  height=covid$nue_posi,
  names.arg=format(covid$FECHA, "%Y"),
  ann = FALSE, 
  bty = "n", 
  tck = 0, 
  xaxt = "n",
  space = 1,
  main= "Casos positivos por día",
  xlab = "Fecha",
  ylab = "Casos positivos",
  col = "blue"
)

# Fechas minima y máxima
x_min <- min(covid$FECHA)
x_max <- max(covid$FECHA)

# Formato del eje X
axis(
  side = 1,
  at = match(seq(as.Date(x_min), x_max, "years"), covid$FECHA) * (1 + 1),
  labels = format(seq(as.Date(x_min), x_max, "years"), "%Y"),
  lwd = 0)

```

##### Fallecidos

```{r casos_ fallecidos}
# Gráfico de barras
barplot(
  height=covid$nue_falleci,
  names.arg=format(covid$FECHA, "%Y"),
  ann = FALSE, 
  bty = "n", 
  tck = 0, 
  xaxt = "n",
  space = 1,
  main= "Casos fallecidos por día",
  xlab = "Fecha",
  ylab = "Casos fallecidos",
  col = "black"
)

# Fechas minima y máxima
x_min <- min(covid$FECHA)
x_max <- max(covid$FECHA)

# Formato del eje X
axis(
  side = 1,
  at = match(seq(as.Date(x_min), x_max, "years"), covid$FECHA) * (1 + 1),
  labels = format(seq(as.Date(x_min), x_max, "years"), "%Y"),
  lwd = 0)

```

